# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='slug',
            field=models.CharField(default=datetime.datetime(2016, 8, 14, 15, 23, 22, 200740, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
