# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 13:29
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=500)),
                ('chapter_date', models.DateTimeField(auto_now_add=True)),
                ('image_urls', models.TextField()),
                ('chapter_index', models.FloatField()),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='chapter_title', unique_with=['series_id'])),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=500)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='series_title', unique=True)),
                ('summary', models.TextField()),
                ('released_year', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=500)),
                ('series_art', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=250)),
                ('rank', models.CharField(max_length=250)),
                ('rating', models.CharField(max_length=250)),
                ('alternative', models.CharField(max_length=2000)),
                ('type', models.CharField(max_length=500)),
                ('banner', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='chapters',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Series'),
        ),
    ]
