# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
